name: base_app
description: A new Flutter project.
version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  micro_core:
    git:
      url: https://github.com/DeividWillyan/-Curso-Micro-Core.git
      ref: v1.0.0

  micro_app_login:
    path: ../micro_app_login

  micro_app_home:
    path: ../micro_app_home

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
